### ISSUE TITLE
protocol: spent outputs not removed from state tree

### ISSUE THREAD

**Issue by jbowens** [chain/chain#1018]
Kudos to @boymanjor for finding this one.

Here's a test with two different transactions, each with a retirement at output index 1. `tx.OutputID(1)` provides the same hash for both: https://gist.github.com/jbowens/434b093c129ae8407e84be32573477c6

I'm not sure if this is a bug in the protocol/bc/legacy mapping to the transaction graph or a bug in protocol/bc?

**Comment by jbowens** [comment]
It look like it might not be a retirement-specific bug. In these two transactions, both of the retirements had identical source ref hashes so, I printed all of the entry hashes for the two transactions and got:

<details>

```
		a.Entries:
	outputid_test.go:25: a.Entries: 5976ff9bb255647a495a6aff03a9e958b12fbffd6829535d61f49b1ebb8eea11
	outputid_test.go:25: a.Entries: ba566fd86b08264125ac2708af7562c0dd68ce4e260d7ed5ffafab295184ddc1
	outputid_test.go:25: a.Entries: 4b655cc6478126e7773d52b6d79a853cb861fe0261f840eb38bcf435bf629480
	outputid_test.go:25: a.Entries: 9913c9d6e3fdeb5eeb41db92f6e391454d76ea620e6639a60cbdfdc6df0a3bb0
	outputid_test.go:25: a.Entries: edfc5f6053ca89b28ebb3636fba4b5ba945a3f0a3b260ea1105994b8ac317706
	outputid_test.go:25: a.Entries: ceb6f5c21510535a3ecb5507b2efbc11314f759c65de60e4e4cefa0e9bb20b76
	outputid_test.go:27:
		b.Entries:
	outputid_test.go:29: b.Entries: 5976ff9bb255647a495a6aff03a9e958b12fbffd6829535d61f49b1ebb8eea11
	outputid_test.go:29: b.Entries: ba566fd86b08264125ac2708af7562c0dd68ce4e260d7ed5ffafab295184ddc1
	outputid_test.go:29: b.Entries: 4b655cc6478126e7773d52b6d79a853cb861fe0261f840eb38bcf435bf629480
	outputid_test.go:29: b.Entries: 9913c9d6e3fdeb5eeb41db92f6e391454d76ea620e6639a60cbdfdc6df0a3bb0
	outputid_test.go:29: b.Entries: 128002b15c0ce3ac3eac893e91a38b452a70f590f6dab804bd22a54d4934b2dd
	outputid_test.go:29: b.Entries: 609aae09096514a64ff1c6fd70956b3287ee6c83f8557d7b92272a91e02aaf33
```

</details>


The `4b655c...` entry is the retirement. The `ba566f...` entry is the mux and the retirement's source. The `5976ff...` entry is the spend. The `9913c9...` entry is an output (the spent output). The other two entries that are not shared between the two transactions are the tx header and the new change output.

From what I can tell both of these transactions spent the `9913c9...` output.

**Comment by jbowens** [comment]
I haven't verified with a unit test yet, but I think the problem is here: https://github.com/chain/chain/blob/main/protocol/bc/legacy/map.go#L79

We populate `OutputIDs` with the hashes of all `*bc.Output` entries in the transaction. But as I understand it, the prevout is also an entry of the `*bc.Output` type. In [state.ApplyTx](https://github.com/chain/chain/blob/main/protocol/state/snapshot.go#L92) we delete the spent outputs and immediately add them back.

I'm going to try to create a contained unit test for it. I'll also try to check if this bug was present in 1.1.3.

**Comment by bobg** [comment]
> I think the problem is here

It looks like some logic got lost (during some branch merge, probably)? ISTR having written something that skips outputIDs when they're also in the list of spent-outputIDs. Can't remember for sure whether that skipping happened in `MapTx` or in `Snapshot.ApplyTx`, but it was probably the latter, since the name of the `TxEntries.OutputIDs` field implies that it's inclusive of both spents and new unspents.

**Comment by kr** [comment]
Should we be iterating over the "results" list to determine what to insert into the utxo set?

**Comment by jbowens** [comment]
AFAICT, `TxEntries.OutputIDs` is only used for inserting into the utxo set, so maybe we can drop that field and just use the ResultIds?

**Comment by bobg** [comment]
The problem is that not all ResultIds are outputs. (Some are retirements, and in the future, some are Who Knows What.) So it should be OutputIDs minus SpentOutputIDs; or equivalently the union of ResultIds and OutputIDs.

**Comment by kr** [comment]
Did you mean intersection? It seems like it would be easiest/safest to base our approach mainly on the resultids list, because that structure is definitive. The outputids and spentoutputids lists, as far as I understand, are auxiliary structures.

E.g. iterate over the results, and whichever ones are outputs, we insert them into the utxo set.

**Comment by bobg** [comment]
> Did you mean intersection?

Er, yes, of course, sorry.
