### ISSUE TITLE
Link to logo in app.json is broken

### ISSUE THREAD

**Issue by allanino** [chain/chain#1024]
The link at [app.json#L5](https://github.com/chain/chain/blob/main/app.json#L5) redirects to a not found page.

I have noticed this because the logo does not show in Heroku when clicking the `Deploy to Heroku` button.

**Comment by dominic** [comment]
Thanks for reporting @allanino - we'll take a look now.

**Comment by dominic** [comment]
Fixed; thanks for letting us know!
