### ISSUE TITLE
pure go windows installer

### ISSUE THREAD

**Issue by kr** [chain/chain#1148]
If we had a windows installer written in pure Go, it would simplify the packaging and testing process for Windows. We would still need to test on Windows, but the build can happen on any platform (e.g. Docker, Mac OS X, Linux).

**Comment by jeffomatic** [comment]
Just brainstorming a requirements list here:

- installs postgres
- installs binaries for chain manager, chain core, and corectl
- adds entire package to official "uninstall" registry
- adds Chain Core to start menu
- handles existing installs gracefully (ideally preserving existing data)

**Comment by kr** [comment]
(Side note: I would like to roll "chain manager" into chain core. We already have a windows-specific monitor process baked into chain core, we don't need another one in a separate binary.)

**Comment by dominic** [comment]
Have we considered the ramifications of not installing Postgres, and having users manage that on their own? I'd wager that's where most of our issues are coming from, and it would be great to let users troubleshoot Postgres with the myriad of resources already available.
