### ISSUE TITLE
Incorrect docs links in dashboard

### ISSUE THREAD

**Issue by devongundry** [chain/chain#1175]
We didn't update the docs links in the placeholder views when we stopped serving docs from Chain Core. They are currently linking to non-existing pages (see attached).

https://github.com/chain/chain/blob/bdcfa23c150a4b415f5c90314fb08607744a0aa5/dashboard/src/features/transactionFeeds/components/List.jsx#L12

https://github.com/chain/chain/blob/8d160896469a2f4418120baf45df76c20fdbd003/dashboard/src/features/shared/components/BaseList/EmptyList.jsx#L30

https://github.com/chain/chain/blob/8d160896469a2f4418120baf45df76c20fdbd003/dashboard/src/features/shared/components/BaseList/EmptyList.jsx#L31

https://github.com/chain/chain/blob/35d1de97abe17c0ba59a548607a7406286f1c31a/dashboard/src/features/assets/components/AssetUpdate.jsx#L74

https://github.com/chain/chain/blob/35d1de97abe17c0ba59a548607a7406286f1c31a/dashboard/src/features/accounts/components/AccountUpdate.jsx#L74

![screen shot 2017-05-06 at 12 14 42 am](https://cloud.githubusercontent.com/assets/28984/25770691/0a5865e0-31f1-11e7-9bf2-535dc16618b7.png)

**Comment by jeffomatic** [comment]
Resolved in #1179
