### ISSUE TITLE
integ: high-availability integration test

### ISSUE THREAD

**Issue by jbowens** [chain/chain#1337]
Currently, we don't have any integration tests covering booting multiple cored processes and connecting them together as a single Chain Core cluster.

It'd be great to have an integration test that:
* Generates a self-signed cert for localhost (likely using code adapted from [crypto/tls/generate_cert.go](https://golang.org/src/crypto/tls/generate_cert.go))
* Sets up _n_ Chain Core data directories all with the above self-signed certificate.
* Launches _n_ cored processes each with its own CHAIN_CORE_HOME.
* Creates a new cluster with one cored using:
  ```
   corectl init
   ````
* Configures the Chain Core
  ```
  corectl  config-generator
  ```

* Connects the remaining _n-1_ cored processes to the cluster.
  ```
  CORE_URL=https://localhost:xxxx corectl join localhost:yyyy
  ```
* Submits a transaction.

**Comment by kr** [comment]
That description sounds kind of like https://github.com/chain/chainprv/tree/main/integ/multinode

Are there things this issue is concerned with that aren't covered in that test?

(Maybe we should move that test to this repo.)

**Comment by jbowens** [comment]
lol whoops, I forgot about that. you're right

**Comment by bsbits** [comment]
@kr your link is not working.
