### ISSUE TITLE
Windows 7 community edition dashboard is empty

### ISSUE THREAD

**Issue by mikailcetinkaya** [chain/chain#1401]
Hello;

Windows 7 ; community edition ; dashboard is empty.
Chrome dev tools say some javascript has mime type text/plain , so must not be executed.
Seems like packaging problem for windows edition.
Mac edition works.

**Comment by jeffomatic** [comment]
We might need some more information to diagnose the issue. Can you try the following:

1. Quit Chain Core.
2. Delete the log file: `del "%LOCALAPPDATA%\Chain Core\postgres.log"` (note that `%LOCALAPPDATA%` might be a different environment variable depending on your version of Windows).
3. Start Chain Core, wait 5 seconds, and then close it.
4. Get the contents of the log file `type "%LOCALAPPDATA%\Chain Core\postgres.log"`
5. Paste the log file contents to a gist and link it here.

**Comment by mikailcetinkaya** [comment]
here is the link.
Thank you
[https://gist.github.com/mikailcetinkaya/6098ebd22c60d2d843101623c5e0abff](url)

**Comment by jeffomatic** [comment]
Sorry, that link doesn't appear to work.

**Comment by mikailcetinkaya** [comment]
https://gist.github.com/mikailcetinkaya/6098ebd22c60d2d843101623c5e0abff

**Comment by jeffomatic** [comment]
Have you tried uninstalling and re-installing the Chain Core application?

**Comment by mikailcetinkaya** [comment]
Yes. I have tried .

**Comment by mikailcetinkaya** [comment]
Configuration Windows 7 pro edition Chrome 59 iis7

**Comment by jeffomatic** [comment]
Would you be able to show us a log after a fresh re-install of Chain Core? There are some warnings/errors in the log you posted that indicate that Chain Core's internal database already exists, which means that log is not from a fresh re-install. I'm not sure yet if those specific error messages are relevant to the actual problem.

**Comment by tylerd** [comment]
I am having this problem with Windows 10 - when running Chain Core it opens http://localhost:1999/dashboard/ but the screen is blank.

Here is the output from the postgres log

```
2017/09/26 09:39:58 =====PG CONFIG LOG=====
LOG:  database system was interrupted; last known up at 2017-09-26 09:37:22 CDT
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/17B0950
LOG:  invalid record length at 0/17B27E0
LOG:  redo done at 0/17B0950
FATAL:  the database system is starting up
2017/09/26 09:39:58 still waiting for postgres ready status: exit status 1
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  database "core" already exists
STATEMENT:  CREATE DATABASE core;
createdb: database creation failed: ERROR:  database "core" already exists
2017/09/26 09:39:59 could not run createdb: exit status 1
2017/09/26 09:39:59 Postgres configured. About to start chain core
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
```
