### ISSUE TITLE
Docker image not generare access token and give error CH009

### ISSUE THREAD

**Issue by didacusAbella** [chain/chain#1409]
Thank you for reporting an issue! Please read the following before submitting:

Github issues are for reporting specific bugs with Chain Core Developer Edition. If you have general questions about Chain Core or questions regarding building an application on Chain Core, please visit our developer support center: 
https://support.chain.com

Enterprise customers can reach out to their support contact directly. 

Please check open issues prior to opening a new issue: 
https://github.com/chain/chain/issues

Please provide the following information. We will only respond to issues that conform to the following format:

#### Environment 
1. Chain Core 1.2
2. Chain Core SDK Ruby 1.2 
3. Host (Linux, Docker)

#### What steps will reproduce the problem?
When I run the docker container with the command exposed in the guide:
docker run -it -p 1999:1999 chaincore/developer
docker service is started and the command is executed as root

#### What result did you expect?
That the container log returned me the access token to access the dashboard
#### What result did you observe?
the console not return access token and give me the following error:
reqid=027e76bb606f6b4879f4 at=api.go:273 t=2017-07-06T11:00:29.284012220Z status=401 chaincode=CH009 path=/info error="not authenticated"
Here a screen:
![schermata da 2017-07-06 13-05-23](https://user-images.githubusercontent.com/11076147/27908409-f029b440-624b-11e7-91a7-275e8e02b2c4.png)

**Comment by jeffomatic** [comment]
Try manually generating a client token:

```
docker exec \
  name-or-id-of-your-container     \
  /usr/bin/chain/corectl create-token id-of-your-token client-readwrite
```

If that works, be sure to record the value of the client token.

**Comment by didacusAbella** [comment]
Thanks it works! And now i close the issue
