### ISSUE TITLE
Chain Core 1.2.1 - Dashboard not loading.

### ISSUE THREAD

**Issue by RyanJEC** [chain/chain#1470]
#### Environment 
Windows app
cored (Chain Core) 1.2.1
build-commit: 2778c2578286caa05f1a9337394b4cb18e22642a
build-date: 1497648197
mockhsm: true
localhost_auth: true
reset: true
http_ok: true

#### What steps will reproduce the problem?
Open http://localhost:1999/
Redirects to http://localhost:1999/dashboard

#### What result did you expect?
Dashboard to load

#### What result did you observe?
Chrome Dev Console
```
Refused to execute script from 'http://localhost:1999/dashboard/dashboard.61118a4e92311d81b5c1.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

Chain server is not serving the js file as script type.

**Comment by croaky** [comment]
Thanks for the bug report and sorry for the trouble.

Would you be willing to try the Docker version at https://chain.com/docs/1.2/core/get-started/install?

**Comment by RyanJEC** [comment]
Docker cannot run on my version of Windows 10.
