### ISSUE TITLE
Error when running chaincore, connection timed out.

### ISSUE THREAD

**Issue by GreenFoxx** [chain/chain#1484]
#1477 
Hey so I am getting an error when I try to run a chaincore container with kitematic in docker from a virtualbox machine, I get this error in the changelog:
Initializing Chain Core...
Chain Core starting...
cored (Chain Core) 1.2.6
build-commit: 156eb8fc23387d9c789b7bb0724f831f41af9195
build-date: 1524009414
mockhsm: true
localhost_auth: true
reset: true
http_ok: true
at=raft.go:221 t=2018-07-15T06:59:09.088995895Z raftid=1
at=main.go:181 t=2018-07-15T07:01:19.888498769Z error="creating migration table: dial tcp 198.105.244.20:5432: getsockopt: connection timed out"
/var/folders/vb/5rt59_2j0mg1x7v_6v7hf56h0000gn/T/tmp.xWK6NdFq/src/chain/core/migrate/migrate.go:21 - chain/core/migrate.Run
/var/folders/vb/5rt59_2j0mg1x7v_6v7hf56h0000gn/T/tmp.xWK6NdFq/src/chain/cmd/cored/main.go:179 - main.main
/Users/dominic/.asdf/installs/golang/1.9.3/go/src/runtime/proc.go:195 - runtime.main
/Users/dominic/.asdf/installs/golang/1.9.3/go/src/runtime/asm_amd64.s:2337 - runtime.goexit

Can someone help me?

**Comment by tessr** [comment]
It looks like your Chain Core process isn't able to reach Postgres. 

However, I should also tell you that, as of earlier this year, we are no longer developing or supporting Chain Core DE. You will have a much better time working with [Sequence](https://chain.com/sequence), our ledger-as-a-service built for tracking and transferring balances in a token format.

**Comment by GreenFoxx** [comment]
@tessr , I'm looking for a blockchain development platform for developing a blockchain for the tokenization of assets. Chain core looked like a great fit for me to do that with but Sequence doesnt seem to mention that what so ever.

**Comment by GreenFoxx** [comment]
Also, I'd like to know how to fix my chain core process in more detail please.

**Comment by tessr** [comment]
Without knowing more about your project, it's difficult to know if Sequence is a good fit. However, you might find that the examples, like https://dashboard.seq.com/docs/example-crypto-exchange, can give you a sense of what Sequence is great at. There are more examples in the sidebar. 

I noticed you're also in our community slack, which is also a great place to get support for Sequence. Support for Chain Core has ended.

**Comment by GreenFoxx** [comment]
I really don't want to know about Sequence because it's not going to work for me. Now you created something and released it to the public, at least do the professional thing and help me fix my problem with it. Also, Chaincore could have been great, I don't know why you don't at least focus part of your effort on the thing YOU created, if only for support. Please don't close this issue until you help me solve my problem.
