### ISSUE TITLE
Failing to add key to SDK signer produces misleading error message

### ISSUE THREAD

**Issue by jeffomatic** [chain/chain#169]
Reproducible on 3579bf1992f423b9f9f246f9f15c8497ee3b3d5f

If you attempt to sign for a spending transaction without first adding the relevant key to the SDK signer object, the signer will not add a signature to the transaction. During the submit step, you are not told that signatures are missing; instead, you will receive a CH736 "Transaction not final" error. While this error is technically correct, it is not the right one to deliver to the user. The error should be that the signature is **missing**, and possibly hint that an xpub needs to be added to the client-side signing object.

The following Ruby script can recreate the problem:

```ruby
$:.unshift ENV['CHAIN'] + '/sdk/ruby/lib'

require 'chain'

c = Chain::Client.new
s = Chain::HSMSigner.new

asset_key = c.mock_hsm.keys.create
s.add_key(asset_key, c.mock_hsm.signer_conn)

account_key = c.mock_hsm.keys.create
# Don't add the key to the signer
#s.add_key(account_key, c.mock_hsm.signer_conn)

asset = c.assets.create(root_xpubs: [asset_key.xpub], quorum: 1)
acc = c.accounts.create(root_xpubs: [account_key.xpub], quorum: 1)

c.transactions.submit(s.sign(c.transactions.build { |b|
  b.issue asset_id: asset.id, amount: 100
  b.control_with_account account_id: acc.id, asset_id: asset.id, amount: 100
}))

c.transactions.submit(s.sign(c.transactions.build { |b|
  b.spend_from_account account_id: acc.id, asset_id: asset.id, amount: 1
  b.retire asset_id: asset.id, amount: 1
}))
```

The immediate fix for this should be to provide a better error message.

Some suggestions for longer-term fixes:

1. The SDK signing interface's `sign` method could return the number of signatures added. Based on the semantics of the multi-HSM signing interface, it is not an error to add zero signatures, but the user could check.
2. Move away from the multi-HSM signing interface, which is solving a future problem (having multiple HSMs in the same application) by making the 99% common case harder and more bug-prone. Adding xpubs to the signer provides for HSM routing that does not actually occur in practice.  Up front, we can provide sign/sign-batch methods directly from the Mock HSM, and remove the artificial constraint that the client must add xpubs to the signer API. This would remove the ["Load key" step](https://chain.com/docs/core/build-applications/keys#load-key) in our setup workflow, which is a significant efficiency.

**Comment by tessr** [comment]
@ameets and I took a crack at fixing the error message, but felt like a longer-term fix would require a product discussion.

**Comment by tessr** [comment]
Closed by #373

**Comment by jeffomatic** [comment]
@tessr Thanks for taking a look via #373. I just grabbed latest and tried the following script:

https://gist.github.com/jeffomatic/0b2057c7ccd0885d92a00f8373b7ed9d

It's a truncated version of the 5-minute guide, but notice that I don't add the newly-created key to the signer. The error message I get is as follows:

```
/Users/jeff/go/src/chain/sdk/ruby/lib/chain/connection.rb:78:in `singleton_batch_request': Code: CH735 Message: Transaction rejected Detail: validation failed in script execution, input 0 Request-ID: a2e90d41f1442c406cb1 (Chain::APIError)
```

From the Chain Core output, I get:

```
app=cored buildtag=dev processID=chain-jeff-chain-2.local-64085-7312d425adeb898aa091 reqid=a2e90d41f1442c406cb1 at=http.go:52 t=2017-02-13T18:55:52.500741700Z subreqid=2006608615f3270caee3 status=400 chaincode=CH735 path=/submit-transaction error="tx 5e73ad7451443f4d185cec56724bdc281be229b25757ab18808bee9e301f90bb: validation failed in script execution, input 0: data stack underflow [prog 766baa2023760280bc497415f5a30c8f430b058615d65cd096a6662854cf9431e668c93e5151ad696c00c0 = DUP TOALTSTACK SHA3 0x23760280bc497415f5a30c8f430b058615d65cd096a6662854cf9431e668c93e 0x01 0x01 CHECKMULTISIG VERIFY FROMALTSTACK FALSE CHECKPREDICATE; args ]: invalid transaction: transaction rejected"
```

Based on #373, what should I expect here? I think the thing I was hoping to get from this bugfix is an error message that no signatures are present, or that one or more inputs are unsigned. But it looks like the transaction makes it as far as running inside the VM...

**Comment by tessr** [comment]
Ugh, sorry--I had only been testing this with the script attached to this issue, which _should_ yield

```
Code: CH737 
Message: Transaction signature missing, client may be missing signature key 
Request-ID: ed250f5175a39faf197d
```

(per #373.)

I'll try that other script and see what I can do

**Comment by jeffomatic** [comment]
Got it. The distinction I'm seeing up front is that the script in the issue fails on a spend action, whereas the script in the gist performs an issuance. Maybe the checks from #373 only cover spending from control programs, and not issuances?

**Comment by tessr** [comment]
Good call--turns out those checks do cover issuances [but only if there's also a spend](https://github.com/chain/chainprv/issues/2022#issuecomment-251521803).
