### ISSUE TITLE
Make Java SDK 1.7 compliant

### ISSUE THREAD

**Issue by fcanevar** [chain/chain#187]
#### Environment 
1. Chain Core Version: latest
2. Chain Core SDK Language and Version: Java latest 
3. Host: Docker on linux

#### Issue
To achieve a more broad usage of the Java SDK it would be nice to make it Java 7 compliant.
I've downloaded the source code and there are a few steps to convert the SDK to Java 7.

1. com.chain.http.Client -> remove lambdas (just create 3 inner classes o anonymous classes)
2. com.chain.api.PagedItems -> implement the remove method (the Java 8 default is throwing a UnsupportedOperationException("remove"))
3. com.chain.signing.HsmSigner.addKey(String, Client) -> add type String to new ArrayList<>

**Comment by ryandotsmith** [comment]
@fcanevar Great suggestion! One of our engineers is working on this now. We should be able to get this resolved soon.

**Comment by fcanevar** [comment]
Thanks a lot!
