### ISSUE TITLE
Breaking changes to the Protocol 1

### ISSUE THREAD

**Issue by oleganza** [chain/chain#239]
This is a draft of a list of breaking (hard forking) changes for P1 before we fully commit to it long-term.

Each feature has its own PR open which is meant to be merged when fully implemented and covered with tests.

### ☑️ ~1. Asset ID without version~ 

Asset ID should not include version tag to allow their reuse in new version of outputs. Initially it was thought as a necessary security feature for non-upgraded nodes, but balancing rules are enough to force assets to balance in such case. And removing version tag allows nice reuse of already deployed asset ids in the new versions of outputs.

PR: https://github.com/chain/chain/pull/261

### ☑️ ~2. Drop RIPEMD160 and SHA1~

They are unnecessary, outdated, and (in the case of SHA1, anyway) weak.

PR: https://github.com/chain/chain/pull/268

### ☑️ ~3. Fixed-length outpoint format~

`SHA3(txid || index || SHA3(output))` - constant size, commits to the output contents directly for HSM-friendliness.

PR: https://github.com/chain/chain/pull/417

### ☑️ ~4. Get rid of all _Optional Hashes_~

Optional Hash is a premature optimization that mixes two concerns: minimizes amount of data to transmit when the hashed string is actually empty, and minimizes amount of data to be hashed. The first one belongs to the transport protocol that can compress common patterns (we have an assumption that such protocol will exist already for other pieces). The second concern (hashing a bit more data) seems to not a serious overhead VS added complexity to implementation.

This is going to be a side effect of the new txgraph redesign. See below.

### 5. Transaction entries

Replace two lists of inputs/outputs with a single flat list of _entries_. Entries can be issuances, inputs, outputs or retirements. We can remove `OP_FAIL` opcode. We can have multiple "reference data" entries, so each party in the transaction can attach that data. Arbitrary accounting rules and behaviours can be added with future entry types.

PR: https://github.com/chain/chain/pull/264

### 6. Review the implementation to check if NOPs are disallowed in tx v1 and allowed in unknown versions.

We need to carefully review implementation of extensibility rules.

### 7. Refactor tx validation spec (compatible change) 

Change validate+validate-well-formedness+apply to validate+apply procedures for txs. Same for block.

### 8. THRESHOLD instruction

It is extra-hard to combine programs in multisig manner which is necessary for consensus programs. Since block VM version is hard to change, we should have a workable THRESHOLD instruction to make it possible to combine individual programs. This will not eliminate, but augment CHECKMULTISIG.

For instance, it could be a TAKE instruction, which takes `m` specified unique indexes from a set of items: `index[m-1] ... index[0] items[n-1] ... items[0] m n TAKE` -> `items[index[m-1]] ... items[index[0]]`. This is the start of a more flexible approach to CHECKMULTISIG and other threshold-type operations.

PR: TBD.

### ~Remove runlimit argument from CHECKPREDICATE~

Program can be tested to be well-formed and in-bounds offline, so the network does not need to impose extra internal runtime limits in addition to the already imposed per-input runlimit.

PR: https://github.com/chain/chain/pull/262

UPDATE: Ivy will target VM2 anyway, so we can avoid cosmetic changes to VM1.

### ~Explicit VERIFY~

Simplify VM validation rules by having outer program and `OP_CHECKPREDICATE` programs not fail, instead of requiring `true` value on stack.

PR: https://github.com/chain/chain/pull/263

UPDATE: Ivy will target VM2 anyway, so we can avoid cosmetic changes to VM1.

### ~Fixed-length integers on VM stack~

In the transaction format, all integers are varints, but on the stack they should be fixed-length 8-byte signed ints for simplicity of implementation and security of smart contracts: fixed-length ints can be concatenated with other data without extra precautions like length-prefixing or extra hashing.

PR: https://github.com/chain/chain/pull/267

UPDATE: Ivy will target VM2 anyway, so we can avoid cosmetic changes to VM1.

### ~Reorder `msg` in CHECKMULTISIG and CHECKSIG~

So that signed message is the first argument, rather than in the middle, making them easier to compile to.

PR: Not to be done in P1.

UPDATE: Ivy will target VM2 anyway, so we can avoid cosmetic changes to VM1.

### ~CHECKMULTISIG -> TAKE~

It is extra-hard to make multisig rule out of signature programs (when each signature is actually a signed program). We need to generalize CHECKMULTISIG to support a selection of a subset (m-of-n) of programs to be executed.

For instance, it could be a TAKE instruction, which takes `m` specified unique indexes from a set of items: `index[m-1] ... index[0] items[n-1] ... items[0] m n TAKE` -> `items[index[m-1]] ... items[index[0]]`. This is the start of a more flexible approach to CHECKMULTISIG and other threshold-type operations.

PR: Not to be done in P1.

**Comment by oleganza** [comment]
Please add comments, additions here. I will incorporate them upstairs in the main text.

**Comment by danrobinson** [comment]
+1 to all of these, except 6 (which was my suggestion, but I think time spent on wedging it into VM1 would be better spent on VM2)

**Comment by danrobinson** [comment]
Additional change: Change `CHECKMULTISIG` so that `msg` is the first argument, rather than in the middle, which makes it much easier to compile to. (Should also change `CHECKSIG` to match. This also lets us gets rid of the `SWAP` in the "hello world" `<pubkey> TXSIGHASH SWAP CHECKSIG` program, as a pleasant side effect).

**Comment by danrobinson** [comment]
In place of a `THRESHOLD` opcode:

6. `TAKE`, which takes `m` specified unique indexes from a set of items: `index[m-1] ... index[0]  items[n-1] ... items[0] m n TAKE -> items[index[m-1]] ... items[index[0]]`. This is the start of a more flexible approach to `CHECKMULTISIG` and other threshold-type operations.

**Comment by danrobinson** [comment]
Drop RIPEMD and SHA1 instructions, since they are unnecessary, outdated, and (in the case of SHA1, anyway) weak.

**Comment by danrobinson** [comment]
Add opcodes for serializing and deserializing "lists" of multiple stack items. These will make it much, much easier to compile to variadic functions like `CHECKMULTISIG` and `CHECKPREDICATE` that take unknown numbers of arguments from the stack. It may help us develop more sophisticated operations. (This may be a good foundation for `TAKE`, for example; see above).

A list would be encoded as a single string of length-delimited items (i.e., each item would be preceded by a varint showing its length in bytes), like so: `3 0xa0e5f6 5 0x40f4e9b7`. Since lists would be stored on the stack as strings, all other opcodes (such as `SHA3`) would work on them as expected. (Some, like `CAT`, would even work out-of-the-box as list manipulation opcodes.)

We could start with just the basics, to be conservative (other list operations like `SLICE`, `LENGTH`, and `APPEND` may turn out to be necessary):

`PACK`: item<sub>n</sub> item<sub>n-1</sub> ... item<sub>0</sub> n -> items[n]
`UNPACK`: items[n] n -> item<sub>n</sub> item<sub>n-1</sub> ... item<sub>0</sub>
`ELEMENT`: items[n] i -> item<sub>i</sub>
