### ISSUE TITLE
[Java SDK] Upload SDK to Maven Central

### ISSUE THREAD

**Issue by cevou** [chain/chain#307]
Please upload the Java SDK to Maven Central. It would make it much easier to integrate the SDK in a project. At the moment it is possible to run the application locally by using a dependency with scope `system`. However, this does not include the jar in the build and it is cumbersome to setup a local repository just for the chain SDK.

**Comment by jeffomatic** [comment]
This is a good idea.

**Comment by dpdornseifer** [comment]
👍

**Comment by jeffomatic** [comment]
We're now hosting the Java SDK from Maven. See https://chain.com/docs/core/get-started/sdk for instructions.

cc: @cevou @dpdornseifer
