### ISSUE TITLE
Docker - Chain Core Initialization Error

### ISSUE THREAD

**Issue by akshithg** [chain/chain#31]
#### Environment 
Chain Core Version - chaincore/developer:latest (docker image)
Host - Docker

#### What steps will reproduce the problem?
`docker run -it -p 1999:1999 chaincore/developer`

#### What result did you expect?
Initialization successful.

#### What result did you observe?
```
Initializing Chain Core...

error: init schema creating migration table: dial tcp `MY_PUBLIC_IP:5432: getsockopt: connection refused
Listening on: http://localhost:1999
Client access token:
Chain Core is online!
```

####
Looks like the the migration is not able to proceed because it cannot to the database. Is there a way to configure the connection on the docker setup?

**Comment by ryandotsmith** [comment]
@akshithg 

Thanks for trying to run Chain Core and sorry you are having troubles :/

We use Github Issues for code specific problems and this is more of a configuration / setup problem. I'm going to close it here, but I'd like to still help you out!

Could we switch over to our help center: https://support.chain.com/hc/en-us
You can create a public post or submit a request.
