### ISSUE TITLE
Ruby SDK requires Ruby 2.1

### ISSUE THREAD

**Issue by tessr** [chain/chain#358]
There's [a line](https://github.com/chain/chain/blob/main/sdk/ruby/lib/chain/access_token.rb#L31) in the ruby sdk that uses [required keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments#required-keyword-arguments) which appear in ruby 2.1. 

We should either specify ruby 2.1 or remove this syntax.

**Comment by jeffomatic** [comment]
Nice catch. I think I favor a 2.1 requirement. We've been using official maintenance schedules as a reason to recommend relative modern software to our users. Official support for Ruby 2.0.x ended in [February of last year](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), so a requirement of 2.1 or 2.2 makes sense.
