### ISSUE TITLE
Spec deviation: asset version 1 output loses suffix data during serialization/hashing

### ISSUE THREAD

**Issue by oleganza** [chain/chain#366]
Output commitments are extensible for all asset versions. It's only tx v1 that disallows use of extra space, but tx v2 might allow that even for existing asset version. Therefore the following code looks incorrect. When we read AV1 output, we should remember the suffix data, and enforce it being empty string only if tx version == 1, but otherwise we need to keep it around in the data structure. Same for AV2 etc: need to read full data and keep it around properly.

Immutable snippet: https://github.com/chain/chain/blob/359827001fc222136648cd34158f80cbbd19c03c/protocol/bc/txoutput.go#L119-L123

Snippet on main: https://github.com/chain/chain/blob/main/protocol/bc/txoutput.go#L119-L123

**Comment by oleganza** [comment]
WDYT @bobg @kr? Do i understand the piece of code above correctly?

**Comment by kr** [comment]
+1, this is a spec violation bug. There are probably several more like this.

In general, I believe we currently only read the exact fields we understand, and discard fields with future versions during deserialization. I think we do this pretty much across the board.

**Comment by oleganza** [comment]
Ok, gotta review and fix all of these then.

**Comment by bobg** [comment]
It would be good if the spec were clarified to say that unrecognized-but-allowed suffixes on input should be preserved for later output.
