### ISSUE TITLE
Spec deviation: input writes prevout unconditionally for all serialization flags

### ISSUE THREAD

**Issue by oleganza** [chain/chain#381]
TxInput always writes the entire prevoutput without checking the serialization flags: https://github.com/chain/chain/blob/9731c85c3473d9ededb00e63c530db8b8c16a64f/protocol/bc/txinput.go#L325

* Per current rules, it should omit the prevout entirely in the context of txid serialization. 
* Per PR #270's rules it should switch between writing the prevout as-is and writing _it's hash_ if we are computing txid.

This issue will most likely be resolved by PR #270.

See also discussion here: https://github.com/chain/chain/pull/270#issuecomment-272296727

**Comment by jeffomatic** [comment]
@oleganza Are you aware if this is still an issue? Following the chain of issues, #270 was superseded by #417, which was superseded by #421, which was merged to main.

**Comment by oleganza** [comment]
@jeffomatic i think the entire premise is no longer relevant, so we can close this issue.
