### ISSUE TITLE
installer/windows: fails to launch on Windows Server 2016

### ISSUE THREAD

**Issue by dominic** [chain/chain#456]

**Comment by tessr** [comment]
Is there any command line output? What's inside `C:\\Program Files (x86)\Chain\postgres` (the postgres startup log)?

**Comment by dominic** [comment]
It hangs at:

```
app=core-manager 2017/02/02 15:47:55 Please wait while we check Postgres...
```

We've seen a similar failure on Windows 7, but that was unsupported. Windows Server 2016 seems to be the same base OS as Windows 10.

**Comment by dominic** [comment]
(note: this was started via an AWS image)

**Comment by tessr** [comment]
Got it. It would be really useful to know what's inside that postgres log (at `C:\\Program Files (x86)\Chain\postgres`).

**Comment by dominic** [comment]
I've asked the user for their log file :+1:
