### ISSUE TITLE
NodeJS snippet documentation missing in Chain Core documentation

### ISSUE THREAD

**Issue by Tkwon123** [chain/chain#479]
Thank you for reporting an issue! Please read the following before submitting:

Github issues are for reporting specific bugs with Chain Core Developer Edition. If you have general questions about Chain Core or questions regarding building an application on Chain Core, please visit our developer support center: 
https://support.chain.com

Enterprise customers can reach out to their support contact directly. 

Please check open issues prior to opening a new issue: 
https://github.com/chain/chain/issues

Please provide the following information. We will only respond to issues that conform to the following format:

#### Environment 
1. Chain Core Version: N/A
2. Chain Core SDK Language and Version: N/A
3. Host (e.g. Mac App, Windows App, Docker): N/A

#### What steps will reproduce the problem?
Try to supply the shortest, simplest set of instructions that reliably demonstrates the problem. Complete running programs or screenshots are helpful too.

A recent change in the site seems to have broken the NodeJS snippets. Visit: https://chain.com/docs/core/build-applications/transaction-basics

#### What result did you expect?

NodeJS snips

#### What result did you observe?

"Snippet "multiasset-within-core" is not in "core/examples/node/transactionBasics.js"

**Comment by jeffomatic** [comment]
Thanks, we'll fix this later today.

**Comment by chrisgarvin** [comment]
Thanks for reporting this, we've gone ahead and resolved the issue. If you're still seeing the error messages in the documentation, go ahead and give your browser a refresh and you should be good to go.

**Comment by Tkwon123** [comment]
Looks wonderful. Thanks guys
