### ISSUE TITLE
corectl config-generator cmd can not config signer's access token

### ISSUE THREAD

**Issue by fengbaicanhe** [chain/chain#498]
I found config-generator cmd can only config signer's pubkey and url,but can not config signer's access token.
This will cause a problem in multi signers environment, the generator will receive 401 response from  signer

**Comment by jeffomatic** [comment]
Hi @fengbaicanhe, thanks for the note. You're correct that `config-generator` doesn't currently support setting access tokens for signer cores, but we're working on improving the interface for performing that kind of configuration--it'll come in a future release.

**Comment by jeffomatic** [comment]
@fengbaicanhe To clarify, you can set the access token via the signer URL itself. Check out the following documentation:

https://chain.com/docs/core/learn-more/configure-block-signers
