### ISSUE TITLE
Different import cause build problem

### ISSUE THREAD

**Issue by fengbaicanhe** [chain/chain#513]
when use `prod` tag build corectl, a build problem appered as follow：

`# chain/cmd/corectl`
`cmd/corectl/main.go:42: cannot use reset (type func(*"database/sql".DB, []string)) as type func(*"chain/database/sql".DB, []string) in field value`

and here have two links might be help
https://github.com/chain/chain/blob/main/cmd/corectl/prod.go#L5
https://github.com/chain/chain/blob/main/cmd/corectl/dev.go#L9

**Comment by bobg** [comment]
Thanks for the report, @fengbaicanhe!
