### ISSUE TITLE
Cannot specify filter using spent_output property

### ISSUE THREAD

**Issue by jeffomatic** [chain/chain#523]
Bug does not appear in 68c85f9b2d15cc69b9107a18f744177128e19c7c (tag `sdk.ruby-1.0.1`), but appears in 7579cb1f655e86bb42afdbf0860aec94af075f5c

Queries such as the following used to be valid:

```
inputs(spent_output.transaction_id='ad929976dbde976d2b74b798632c762fb8146ad0c0d1e0d883487fcee1ebb2c4')
```

However, I now get the following error message:

```
Code: CH602 Message: Malformed query filter Detail: invalid attribute: spent_output Request-ID: b2e381c701e04ec73e65
```

`spent_output` is deprecated in 1.1, but should still work until the property is fully removed.

**Comment by jeffomatic** [comment]
@jbowens Any idea off the top of your head what might cause this?

**Comment by bobg** [comment]
https://github.com/chain/chain/pull/440 was intended to restore `spent_output` to annotated inputs after it had been replaced with `spent_output_id` in https://github.com/chain/chain/pull/421. But https://github.com/chain/chain/pull/440 included no tests for the new functionality. Is it known ever to have worked?

**Comment by jeffomatic** [comment]
I tried out the filter in 68c85f9b2d15cc69b9107a18f744177128e19c7c and it works, so it seems that something broke it since then.

**Comment by jbowens** [comment]
I think this slipped through during the filter rewrite. I think the most expedient way to fix this is to add a new column to `annotated_inputs` that is a nullable `jsonb` column and update it to be the spent output object. Backfilling the object might be hard. We might need to pull it out of the `annotated_txs.data` column.

**Comment by jeffomatic** [comment]
I think we can probably skip the backfill, assuming you're talking about it as a migration step.
