### ISSUE TITLE
querying for local assets results in CH602 error

### ISSUE THREAD

**Issue by jeffomatic** [chain/chain#567]
To reproduce:

1. Open dashboard
2. Create a new asset
3. In the Assets list view, type in the following query: `is_local='yes'`.
4. A CH602 error will appear, even though the query is legal.

**Comment by erykwalder** [comment]
:eyes:

**Comment by jeffomatic** [comment]
Two things I'm noticing:

1. `Type: filter.Bool` should probably be `Type: filter.String`: https://github.com/chain/chain/blob/main/core/query/sql.go#L18
2. The wrong error message is printed: https://github.com/chain/chain/blob/main/core/query/filter/typecheck.go#L111

I'm currently seeing:

```
Error: Code: CH602 Message: Malformed query filter Detail: = expects integer or string operands Request-ID: 227ed932a2179748ea94
```

It should have mentioned that the operator expected a boolean value.

**Comment by erykwalder** [comment]
I think those columns actually use bool values though.

**Comment by jeffomatic** [comment]
Hmm, maybe we're thinking of something different? The filter language doesn't have examples of boolean r-vals yet, and it wasn't until @jbowens rewrote the indexing system that we could query against booleans at all. I ran into this because I was running our documentation examples against the current Chain Core, and I'm pretty sure they worked for our 1.0.x builds.

**Comment by erykwalder** [comment]
The SQL value is a boolean:
https://github.com/chain/chain/blob/main/core/schema.sql#L240

So I think just changing the column type wouldn't work. The reason that error message is printed is because you can only compare strings and integers right now.

**Comment by erykwalder** [comment]
I'm wondering if we can change those values to actually use boolean representation, rather than "yes"/"no" and add boolean values to the filter expressions.

I think other options would end up being a bit hacky.

**Comment by jeffomatic** [comment]
I actually changed `Type: filter.Bool` to `Type: filter.String` and the examples run. Maybe you're referring to `SQLType`?

**Comment by jeffomatic** [comment]
It's a similar setup as `outputsTable`'s `is_local` field (in the same file).

**Comment by jbowens** [comment]
Yeah, that's a typo. It should be `Type: filter.String`. See [this commit message](https://github.com/chain/chain/commit/35b6218800339350ffa67de6ef9b55222b93d03b). The reason this works:

> Because `'yes'` and `'no'` happen [to be valid PostgreSQL boolean literal
values](https://www.postgresql.org/docs/9.5/static/datatype-boolean.html), existing queries like `asset_is_local = 'yes'` will continue to work without additional
changes. When we add support for true booleans, we'll need to make sure not to break backwards compatibility.

**Comment by erykwalder** [comment]
Good to know

**Comment by jbowens** [comment]
I think the typecheck error message is correct. Ex, if you perform a query like

```
inputs(asset_alias = 'gold') = 'cantelopes'
```

**Comment by jeffomatic** [comment]
Got it. So `Type: filter.Bool` should just never happen for now.
