### ISSUE TITLE
core/pin:  processors fail to make progress after booting from snapshot

### ISSUE THREAD

**Issue by jbowens** [chain/chain#643]
If we boot from a state snapshot (and don't have all of the blocks from 1 to _n_), the block processors get stuck [here](https://github.com/chain/chain/blob/main/core/pin/pin.go#L209) trying to process a block that we never downloaded.

Seems like the correct solution is to altering the bootstrapping process to download the snapshot and corresponding block, initialize all of the pins to the snapshot's height and then start the block processors. That might require quite a bit of refactoring.

**Comment by jbowens** [comment]
@devongundry — This is the bug you found.

**Comment by jeffomatic** [comment]
> That might require quite a bit of refactoring.

Obligatory question: is there a quick fix that will unbreak the release? Obvs we'd want to avoid side effects other than temporarily-gnarly code.

**Comment by kr** [comment]
> Obligatory question: is there a quick fix that will unbreak the release? Obvs we'd want to avoid side effects other than temporarily-gnarly code.

Yeah this looks like a classic example where we might fix the same bug in two completely different ways: the long-term good fix on main involving a lot of refactoring, and a very conservative surgical fix on the release branch, aiming to minimize risk of other breakage.

**Comment by jbowens** [comment]
The refactoring may not be as invasive as I thought. See #644.
