### ISSUE TITLE
internal rpcs fail with tls configured

### ISSUE THREAD

**Issue by kr** [chain/chain#674]
cored uses a hard-coded http (not https) scheme to connect to other cored instances. If cored is configured in production mode, it redirects all http requests to https, but the client side of the RPC doesn't follow redirects.

**Comment by jbowens** [comment]
Fixed in `1.1-stable` with #675 but still outstanding on main.

**Comment by jbowens** [comment]
Seems like the fix for `main` will probably involve exclusively using TLS. We can talk about it today at the 1.1 retro.

**Comment by jbowens** [comment]
Since the TLS everywhere work is delayed until 1.3, we'll need to do a fix similar to what we did for 1.1.x in 1.2. I think we can just pass in a `core.TLS` `RunOption` if `*tlsCrt != ""` which tells `forwardToLeader` to use https.

**Comment by kr** [comment]
SGTM, but I think maybe this should wait until after #898 lands. Even if we don't have TLS everywhere, we might have TLS everywhere-in-production, and the way to detect it will be different (i.e. a build tag).

**Comment by kr** [comment]
Fixed on main in #675.
