### ISSUE TITLE
Transaction Feeds do not acknowledge blocks > 125 unless recreated  (nodeJS SDK)

### ISSUE THREAD

**Issue by Tkwon123** [chain/chain#714]
Thank you for reporting an issue! Please read the following before submitting:

Github issues are for reporting specific bugs with Chain Core Developer Edition. If you have general questions about Chain Core or questions regarding building an application on Chain Core, please visit our developer support center: 
https://support.chain.com

Enterprise customers can reach out to their support contact directly. 

Please check open issues prior to opening a new issue: 
https://github.com/chain/chain/issues

Please provide the following information. We will only respond to issues that conform to the following format:

#### Environment 
1. Chain Core Version: 1.0.2
2. Chain Core SDK Language and Version: Node SDK
3. Host (e.g. Mac App, Windows App, Docker): Tested on both Ubuntu and Mac (both using Docker)

#### What steps will reproduce the problem?
Try to supply the shortest, simplest set of instructions that reliably demonstrates the problem. Complete running programs or screenshots are helpful too.

1) Create a blockchain, mock HSM key
2) Create an asset, account, and transaction feed
3) Open transactions feed in web console, and issue assets (that create transactions) to create blocks > 125

#### What result did you expect?

Viewing the transaction feed should acknowledge blocks >125. As seen in images, the generator blocks register = 146
![pasted image at 2017_03_07_09_31 am 2](https://cloud.githubusercontent.com/assets/8537880/23668862/00310f4c-0328-11e7-986f-f0d949bc2610.png)

The transaction feed halts at 125. 
![pasted image at 2017_03_07_09_31 am 1](https://cloud.githubusercontent.com/assets/8537880/23668863/0058f462-0328-11e7-8c47-3ca8c68c5a9f.png)

This has been replicated a few times on both Macs and Ubuntu 16.04. 

#### What result did you observe?

Transaction feed does not emit any results greater than 125:

TO FIX THIS ISSUE, you can recreate the same transaction feed and chaincore will catch up and emit the results.

**Comment by dominic** [comment]
Thanks @Tkwon123 - we're taking a look now.

**Comment by chrisgarvin** [comment]
Hi @Tkwon123 , thanks for reporting this. I went ahead and created a test environment  using Chain Core 1.0.2 and our 1.0.2 version of the Node SDK. I followed your repro steps, but did not see the transaction feed halt at 125. Would you by chance be able to provide a code snippet in the form of a gist which shows the code that you're running locally that causes this error? Thanks!

**Comment by Tkwon123** [comment]
Hey @chrisgarvin thanks for looking into this. 

I'm sorry I actually inadvertently missed an elusive repo step... Following step #3, please try restarting the chaincore container and running another transaction (this was happening as I was sleeping my computer). 

I reproduced the event again as seen below following the steps (note the transaction count vs the ack on the feed). 

![screenshot from 2017-03-07 21-04-03](https://cloud.githubusercontent.com/assets/8537880/23689737/555632cc-0382-11e7-81d5-48db4d56f059.png)
![screenshot from 2017-03-07 21-04-16](https://cloud.githubusercontent.com/assets/8537880/23689757/87051590-0382-11e7-8293-f10472f23737.png)

As for the code, I'm just using the REST API to POST a 'issue' transaction against the chain core (there really is no error outside of a lack of response). I can share if this added step doesnt raise the issue.

**Comment by chrisgarvin** [comment]
Thanks @Tkwon123 for the additional repro steps. Looking into this!

**Comment by chrisgarvin** [comment]
Hi @Tkwon123 , just wanted to check back in. At this point, I'm still unable to repro it on my end mimicking your setup (docker, Chain Core 1.0.2, Chain node sdk version 1.0.2). I'll continue looking into it, and having others on the team as well. In the meantime, could you send me the code you are using while automating these issuance transactions and building the transaction feed?

Thanks so much, and have a great weekend!

**Comment by Tkwon123** [comment]
Hey @chrisgarvin appreciate the followup. 

Here's the script I use to post transactions:
https://gist.github.com/Tkwon123/150b932380234afe11fb8ed0b4fecd0f

Just to note, I have an API that is wrapped around the chaincore just to do some of the data massaging for writes to the chaincore (within the script, it lives on port 3000). You'll see that the body of the createTransactions.js follows the same format of the issue transaction listed within your guys' documentation so nothing fancy should be happening here. 

This is the exact sequence I just ran to replicate the issue:

1) Create chaincore (including setup of new blockchain)
2) Create account
3) Create asset
4) Run script for transaction 125 times (need to run individually to prevent multiple transactions from being stored in the same block)
5) Restart the chaincore
6) Enter another transaction
7) Check http://localhost:1999/dashboard/transaction-feeds to see if transaction was ack'd

FYI, I tried bumping up to chaincore:1.1.3 and no luck. Let me know if there's anything else I can try as I seem to be able to consistently replicate this.

**Comment by chrisgarvin** [comment]
Hey @Tkwon123, apologies for the delay in getting back to you about this. I believe what's happening is that when the Chain Core is restarting, the transaction feed being consumed is halted, which is expected behavior. This error is generally caught when checking for it within the code that consumes the Transaction Feed (what you'll want to do is query this particular transaction feed by it's alias and re-consume it when the Chain Core is back online to pick up further transactions properly).  When you have a moment, could you do me a favor and show me the code where you are creating/consuming the Transaction Feed in order for me to verify that errors are being caught properly during consumption? Thanks so much!

**Comment by Tkwon123** [comment]
Hey thanks @chrisgarvin for the response. The strange thing is that the feed _does_ successfully pick up further transactions when blocks are at heights <125. I can pretty freely restart the container running the app at all points of the cycle until that magic number. 

To your point though, let me do a bit more digging next week to see if I can replicate this issue in another script outside the current setup (which is currently publishing to RabbitMQ). BRB!

**Comment by Tkwon123** [comment]
Hey @chrisgarvin A new repository with instructions to replicate this issue can be found here: https://github.com/Tkwon123/chain-feed-issue

When you have a moment, would you mind giving that a whirl and seeing if any easy explanation exists for this behavior? 

Let me know if any step in the README is ambiguous and I'd be happy to clarify

**Comment by chrisgarvin** [comment]
Hey @Tkwon123 , thanks so much for the detailed README, this was extremely helpful. I was able to verify on my end, which led to locating the issue causing it. I've gone ahead and pushed a fix, so if you go ahead and update to version 1.1.1 of our Node SDK, the issue should be resolved. Thanks again!

**Comment by Tkwon123** [comment]
@chrisgarvin np happy to help out. Mind also pushing this code to dockerhub? https://hub.docker.com/r/chaincore/developer/ has the 1.1.1 tag but doesnt seem like it has the updated push

**Comment by chrisgarvin** [comment]
@Tkwon123 you should be able to modify your `package.json` file to reflect the newly updated version of `chain-sdk` of "1.1.1", which is where the fix for this issue lives.

**Comment by Tkwon123** [comment]
Opps yeah sorry long day. Thanks!
