### ISSUE TITLE
core/query: race condition annotating remote issuances

### ISSUE THREAD

**Issue by jbowens** [chain/chain#76]
There's a race condition when a block lands that includes a transaction issuing a new, remote asset. Since block indexing callbacks run in parallel now, it's possible for the `core/query` callback to annotate the transaction before the `core/asset` package has recorded the new asset in the database. The resulting annotated transaction will be missing the asset definition.

Transactions using the asset in any subsequent blocks will be correctly annotated with the asset definition.

Possible solutions:
1. Don't run block callbacks in parallel. This would impact performance.
2. Include the block height when calling out to the asset package to annotate transactions. In the asset package's annotation function, explicitly wait until the asset package's callback has finished indexing the block at the provided height.
3. When annotating a transaction, if the asset isn't indexed in the database, manually pull the asset definition out of the input's issuance program. We'll also need to keep it around through the duration of annotating the block, because other inputs/outputs/transactions within the block may also refer to the new asset.

**Comment by bobg** [comment]
Proposal: instead of invoking a bunch of functions, each processing the whole block, `CommitBlock` could feed the transactions to a callback pipeline, which can be set up to process each transaction in a strict dependency order. A worker pool would pull from this pipeline, processing many transactions in parallel, but each transaction's processing steps would always be in the same order.

**Comment by kr** [comment]
I like something along the lines of option 2 or 3. IMO this stuff shouldn't really be the concern of the chain/protocol/... packages. I'm wary of adding more logic in there to address this. If we did chain/chainprv#2244, we'd have more room to maneuver to let various components synchronize with one another.

For example, in core/query:

```
func Process(height int64) {
	for {
		height++
		assetManager.WaitForBlock(height)
		b := chain.GetBlock(height)
		annotate(b)
	}
}
```

So assetManager.WaitForBlock is like protocol.Chain.WaitForBlock except it also waits for core/asset to do its thing.

**Comment by jbowens** [comment]
> So assetManager.WaitForBlock is like protocol.Chain.WaitForBlock except it also waits for core/asset to do its thing.

Yeah, I like that too. I think we'll need something similar to that for the account package once we have block processors. I could imagine that we wouldn't want the submit endpoint to return until the UTXOs are indexed. Instead of calling protocol.Chain.WaitForBlock, the submit handler could call accountManager.WaitForBlock.
