### ISSUE TITLE
Chain Core on Mac initialization visual never goes away. 

### ISSUE THREAD

**Issue by turlockmike** [chain/chain#78]
#### Environment 
1. Developer Edition 1.0.1
2. Mac

#### What steps will reproduce the problem?
Install latest version of Chain Core for Mac and Run

### What I was expecting
For the visualization to go away

#### Screenshot

http://i.imgur.com/mcf68j3.png

**Comment by marjoriekasten** [comment]
@turlockmike 

Thank you for downloading Chain Core! We're sorry you're having issues. 

We use Github Issues for code specific problems and this is more of a mac app issue. I'm going to close it here, but we'll definitely help you out in our support center: https://support.chain.com

Please open a ticket and we can help debug the problem!
