### ISSUE TITLE
proposal: block processors

### ISSUE THREAD

**Issue by kr** [chain/chain#82]
[Note: this document was originally written a few months ago, and it's slightly out of date in a few places where it talks about "current" behavior.]

Currently the protocol.Chain calls a set of callbacks whenever a block is applied to the chain. Let’s call the block callbacks _processors_. Currently, committing a block and running the processor happens in lockstep. The next block will be validated once all the processors for the previous block have finished.

There are some problems with the current situation.
# Problem 1: Synchronous

It’s possible for a processor to encounter an error. Maybe the database’s disk has filled up, or we have a syntax error in one of the SQL statements. These sorts of errors are different from validation errors. If a block fails validation, we need to reject it and wait for a valid block. The system halts entirely. But once the block is validated, we are _obligated_ to process it. If a processor fails for any reason, it’s our fault, and we need to alert a human and fix the error, so we can resume processing.

Currently, we handle processor failure (when we handle it at all) by crashing the process, meaning we stop everything, even validating new blocks and serving non-blockchain requests such as “list account managers”. This is bad for availability.
## Solution 1a: Async

While a processor is failing, we can certainly continue to validate new blocks, as long as we keep track of which ones haven’t yet been processed. The system as a whole is already asynchronous, so this won’t change our basic assumptions. It will allow us to provide partial availability (validating blocks, serving requests) even while processors are failing.

This means we have, notionally, two pointers: one pointing to the last block that was committed and another one pointing to the last block that was processed. The processor pointer necessarily trails the commit pointer. They can be equal, but processors always run after a block is committed. (For crash recovery, these pointers also need to be put somewhere persistent, but for our purposes here, that is an implementation detail.)

The processor pointer also serves a second function: it “pins” all subsequent blocks to persistent storage. Processing is the last step in the pipeline for ingesting each block. Once processing has finished, that block can be released—it’s okay to prune.
## Solution 1b: Concurrent

We can take the idea of partial availability further. We’ve decoupled failure of validation from failure of the processors, and we can also decouple failure of one processor from another. Giving each processor a name and its own pointer lets us continue running most of them even when one has failed. This implies they will run concurrently.

With multiple processor pointers, it’s safe to prune the min.
## Section 1c: Distributed Concurrency

The core leader is responsible for launching processors but shouldn't have sole responsibility for executing them. If other servers in the same core have cycles to spare, the leader should be able to farm out the execution of a processor to another server.
# Problem 2: Transitions

Imagine a Chain Core with all optional features turned off: no account manager, no issuer, no explorer, no long-term block archiving. All it does is ingest blocks and validate them. It’s been running this way for months. Now let’s say the operator wants to turn on all services and optional features. In theory, is this easy? Is it even possible?

For some services, no problem. Creating a new account manager is easy. Generate an xpriv and begin indexing UTXOs for known public key hashes. By construction, the set of UTXOs held by the new account manager is empty at the time it’s created.

For other services, impossible. Indexing [historical UTXOs](https://trello.com/c/Hl6TgJwq/37-historical-utxos) requires knowing the history. In this example, the history has been thrown away.

We don’t have a coherent way to handle these transitions, or to express which ones are safe and which aren’t.
## Solution 2a: DB Config

The Chain Core shouldn’t use environment variables to control which features and services are enabled. Instead, it should store the configuration in database tables and mediate access with logic that can prevent unsafe configurations and make safe transitions more convenient.

If block archiving is enabled, then essentially any service can safely be enabled (even though it might take a long time to catch up). If block archiving is disabled, it can in principle be enabled if at least one other node on the network has a complete archive. Enabling block archiving will cause the system to begin fetching all blocks from other nodes, and then other features can be enabled.

There are even some features that don’t need to start from the very beginning, but do need at least a complete copy of the current state. Historical UTXOs is one such feature. We can support this style of transition using the same principles.
## Solution 2b: Pull (not Push)

Finally, considering all these things, I think callbacks are inside out. It might be better instead to have processors request blocks from the protocol.Chain and explicitly update pointers with `GetBlock(height)`, and `Pin(pointerName, height)`  and `Release(pointerName, height)` calls.

Then, we have a somewhat more straightforward path to enable a feature F that requires indexing the entire blockchain. The first step is to pin block 1 (which guarantees that all subsequent blocks are stored locally). If this operation fails, it’s not safe to enable F, and block archiving needs to be turned on first. Once that’s done, F can proceed at its own pace, fetching blocks and processing them until it’s all caught up. (It’s even safe to turn block archiving off again, any time after F has been enabled, because it’s pinned the necessary blocks. In that case, the blocks will be automatically discarded as they’re no longer needed.)

A similar process applies if the feature can start from a more recent state snapshot.

**Comment by jbowens** [comment]
Is this good to close out?

**Comment by kr** [comment]
Yeah I think so! :tada:
