### ISSUE TITLE
API proposal: mutable account and asset tags

### ISSUE THREAD

**Issue by jeffomatic** [chain/chain#828]
Up to now, we've treated account and asset tags as immutable data. We've had requests from various customers about the ability to update tags. In terms of the accounts and assets themselves, this is a valuable feature, and trivial to implement.

However, we've been reluctant to make the change because of complications due to transaction annotations. A simple update would ignore the effect on annotations. Depending on the context, this may or may not be desirable. If, instead, you want the tags to behave more like they would in a relational database (I'd argue this would be the default user assumption), you'd need a background job system to update pre-existing annotations with the updated tags. The latter is widely regarded as a fairly gnarly task.

## The easy solution

1. We allow updates to account and asset tags without worrying its potential effects on annotations.
2. Transactions will be annotated according to the state of the asset/account tags at the time of block processing.
3. We'll document the effects on annotations and querying.

The benefit of this solution is that it allows users to use tags a mutable data store, and it will allow for better flexibility when querying for assets and accounts. The downside is that there's some footgun potential with respect to tag-centric transaction queries, including balance queries.

The request structure for these calls is more or less self evident, i.e. something like:

```
POST /update-account-tags

{
  <"id"|"alias">: ...,
  "tags": {
    "foo": "bar",
    "foobar": "barfoo",
    ...
  }
}
```

## Relatedly

The easy solution above tempts a couple of possible updates:

1. Introduce a `/tag-asset` API call that allows Chain Core instances to alias and tag assets that did not originate on the local core.
2. Allow aliases to be updated. On the one hand, the alias is just a glorified tag. On the other, since aliases are pretty important to the most common queries (such as balances), it may be better to ensure that they're immutable.

**Comment by kr** [comment]
Big fan of the easy solution here. It sounds great to me.

If we present+document it right, then I think+hope the historical annotations will be okay. Seems like a matter of education.

> On the one hand, the alias is just a glorified tag.

I am not sure I 100% agree with this. Can two accounts have the same alias?

**Comment by dominic** [comment]
For the request structure, we'll need to indicate the account or asset `id` as well. That makes the suggested structure a little ambiguous:

```
POST /update-account-tags

{
  "id": "acc123",
  "foo": "bar",
  "foobar": "barfoo",
  ...
}
```

Combining the easy solution and related point 1, I'd like to see something more like this:

Endpoints:
```
POST /update-asset
POST /update-account
```

Request:
```
{
  "id": "acc123",
  "tags": {
    "foo": "bar",
    "foobar": "barfoo",
    ...
  }
}
```

We don't have to decide whether alias is updatable at this point, but it be a straightforward extension in the future.

**Comment by jeffomatic** [comment]
> I am not sure I 100% agree with this. Can two accounts have the same alias?

Right, it's not a perfect comparison. At the same time, the uniqueness constraint in and of itself isn't a reason to disallow updates.

One thing I like about making the alias updateable is that it unifies the update-tag operation with the (currently-non-existent) tag-asset operation, with PUT-style semantics.

**Comment by jeffomatic** [comment]
@dominic Yes we'd need an ID in that RPC, I blew it. Updating...

**Comment by jeffomatic** [comment]
> One thing I like about making the alias updateable is that it unifies the update-tag operation with the (currently-non-existent) tag-asset operation, with PUT-style semantics.

On second thought, this is not something we'd necessarily want. In particular, we may want to use the alias as the lookup key when performing a tag update, so updating the alias in the same call is kind of weird.

**Comment by dominic** [comment]
> On second thought, this is not something we'd necessarily want. In particular, we may want to use the alias as the lookup key when performing a tag update, so updating the alias in the same call is kind of weird.

I think it's going to be simpler and match expectations to address objects for updating by ID. If you only know the alias, you'll need do a look up first.

More than accounts, I think updating the aliases of _external_ assets has a large experience benefit to the user in a world where we're frequently pushing the convenience of aliases.

**Comment by jbowens** [comment]
Previously, accounts and assets were immutable once they were created. I think we've been making use of that fact in some of our scenarios where two parties share a Core. Are we going to need to revisit that as part of the authorization changes because of this?

**Comment by jeffomatic** [comment]
> I think it's going to be simpler and match expectations to address objects for updating by ID. If you only know the alias, you'll need do a look up first.

The consistency curmudgeon in me wants to keep lookup-by-alias a common operation across all API endpoints, but I agree that it complicates the tag/track-somebody-elses-asset operation, and I haven't thought of a clean solution for that. Yet...?

**Comment by devongundry** [comment]
Dom and I just talked through this a bit IRL. The State Street case for updating tags will happen often, so I'd rather not make them do a double lookup. Also, it feels like the primitives of alias and tags are actually different enough to warrant separate endpoints.

How about:

```
POST /update-asset-tags
POST /update-account-tags

{
  <"id"|"alias">: ...,
  "tags": {
    "foo": "bar",
    "foobar": "barfoo",
    ...
  }
}

```

and 
```
POST /update-asset-alias
POST /update-account-alias

{
  <"id"|"current_alias">: ...,
  "alias": ...
    ...
  }
}
```

Regarding `current_alias`: there is some sort-of prior art when you change a password, asking for "current password".

**Comment by jeffomatic** [comment]
@devongundry I'm fine with that. But in the spirit of password changes, how about `current_alias` and `new_alias`?

Also, does this mean you are generally on board with changing aliases?

**Comment by jeffomatic** [comment]
@jbowens 

> Are we going to need to revisit that as part of the authorization changes because of this?

I didn't make the connection to authz right away...can you clarify a bit how tags and/or aliases relate to that?

**Comment by jbowens** [comment]
> I didn't make the connection to authz right away...can you clarify a bit how tags and/or aliases relate to that?

We have a few cases where multiple parties are accessing the same Core. If assets and accounts are no longer immutable (because their tags are mutable), we don't have any mechanism preventing them from modifying each other's accounts and assets.

**Comment by jeffomatic** [comment]
> If assets and accounts are no longer immutable (because their tags are mutable), we don't have any mechanism preventing them from modifying each other's accounts and assets.

Hmm that is a pretty interesting issue, although TBH my take has been that any client of a particular core has had more or less admin-level access to the core. We have (somewhat sneakily) been living in a world where clients can mess with each other to an extent; consider the scenario where you and I are clients of the same core: I can already read your balances, and I can also delete your access tokens. I think the any-client-is-god model is our default; the fact that different clients couldn't edit each other's assets/accounts was an accident rather than an intentional authorization measure.

Are we heading toward a future where our ACLs are scoped to accounts and assets? If so, how quickly, and how would we deal with visibility issues like annotations?

(insert exceedingly well-written, witty, though-leadery Github-Issues-needs-threads screed here)

**Comment by jbowens** [comment]
> We have (somewhat sneakily) been living in a world where clients can mess with each other to an extent;

Until now, I think access tokens have been the only mechanism through which you can alter another party's data. Yes, you can read everything, but most of our data has been immutable (deliberately or not).

>  I think the any-client-is-god model is our default; The fact that different clients couldn't edit each other's assets/accounts was an accident rather than an intentional authorization measure.

Agreed. This discussion probably should be in the authorization issue, but this brought it top of mind for me because it has practical consequences for some of our existing Chain Core deployments. Our authorization model _has_ always been at the Core level.

**Comment by devongundry** [comment]
@jeffomatic. My main motivation is to alias an asset that you didn't create in your core. That said, I'd be ok with only /set-asset-alias if one doesn't exist. But I don't have strong conviction on not mutating existing aliases.

Regarding naming, maybe "alias" and "new_alias" is better, so we can be consistent with the "id" || "alias" convention as the identifier

**Comment by jeffomatic** [comment]
Superseded by #857
