### ISSUE TITLE
Nondeterministic transaction validation failures

### ISSUE THREAD

**Issue by jeffomatic** [chain/chain#834]
We're seeing intermittent test failures, mostly from Wercker CI, but some have repro'd locally as well. Please report incidences here.

**Comment by jeffomatic** [comment]
https://app.wercker.com/Chain/chain/runs/java/58dd474c8e77b3000169725f?step=58dd476d61eee4000132760a

**Comment by jeffomatic** [comment]
From @bobg on 2017/3/24: https://app.wercker.com/Chain/chain/runs/java/58d57ddb3b84e800018ec03e?step=58d57df6ca1fbb00011d6d46

**Comment by jeffomatic** [comment]
From @jbowens on 2017/3/28:
https://app.wercker.com/Chain/chain/runs/java/58dab9328e77b30001673e44?step=58dab94378bfa50001692c1c

**Comment by jbowens** [comment]
Are we able to build our wercker builds with `-race`? The race detector requires cgo which we have disabled in wercker builds.

**Comment by jbowens** [comment]
Captured a failure locally. https://gist.github.com/jbowens/5c270ec04d8b449ec5da6bc0ffea0c4d

**Comment by jbowens** [comment]
Verified that it nondeterministically fails validation. I was testing against the SHA 5c8fd89380e519d1d5caab3f3996f0cdf3c63617. Since we just landed some validation changes, I'll try to repro on the latest first.

**Comment by jeffomatic** [comment]
> Captured a failure locally

Cool, updated the description so it doesn't incorrectly suggest that it's a Wercker problem.

**Comment by jbowens** [comment]
VM trace output during a failure: https://gist.githubusercontent.com/jbowens/5c270ec04d8b449ec5da6bc0ffea0c4d/raw/ee9b8cc1726d9be940414f3895462bccc0a41e92/vm%2520output

**Comment by bobg** [comment]
Can you capture a VM trace during success, for comparison?

**Comment by jbowens** [comment]
Success https://gist.githubusercontent.com/jbowens/5c270ec04d8b449ec5da6bc0ffea0c4d/raw/55b2af4ac8649ccced879204cba4f5447b3c4e3c/success%2520vm%2520output

**Comment by jbowens** [comment]
Looks like the output ID opcode was returning something different?

![screen shot 2017-03-30 at 4 51 30 pm](https://cloud.githubusercontent.com/assets/867352/24530791/3097f116-1569-11e7-9707-092edf105dad.png)

**Comment by jbowens** [comment]
I think these loops were the culprit(s): https://github.com/chain/chain/blob/5c8fd89380e519d1d5caab3f3996f0cdf3c63617/protocol/bc/txtransaction.go#L109-L117

**Comment by jbowens** [comment]
Ok, yeah, we were creating the VMContext expecting `SpentOutputIDs` to be ordered correctly: https://github.com/chain/chain/blob/5c8fd89380e519d1d5caab3f3996f0cdf3c63617/protocol/bc/vmcontext.go#L84

But when we populated `SpentOutputIDs`, it was in random map order: https://github.com/chain/chain/blob/5c8fd89380e519d1d5caab3f3996f0cdf3c63617/protocol/bc/txtransaction.go#L76-L117

This was all refactored in af099a4ea31d86e1b3a988b6da1d22b0e7d5243b
which fixed the bug, so we should be good now.

**Comment by jeffomatic** [comment]
@jbowens Did this bug make it out into any of the releases?

**Comment by bobg** [comment]
Nice work @jbowens, thanks!

@jeffomatic, this was part of the entries-validation work, which I _think_ has been excluded from all releases so far.
