### ISSUE TITLE
don't compile protoc

### ISSUE THREAD

**Issue by kr** [chain/chain#890]
Our docker image for CI is compiling protoc from source, which takes an ungodly amount of time. But they have binary releases we can download.

https://github.com/google/protobuf/releases

Let's look in to that.

**Comment by kr** [comment]
One possible reason: maybe they don't run on CentOS 6 (glibc 2.12).

**Comment by boymanjor** [comment]
The official protobuf binaries are built with an incompatible version of glibc. What do you think of pulling the compiled binary out of the image and throwing it up on s3? We can add downloading it as a part of the image build.

**Comment by bobg** [comment]
Worth mentioning: although generated Go code in proto3 is not supposed to contain getters for simple scalar fields (as documented [here](https://developers.google.com/protocol-buffers/docs/reference/go-generated#singular-scalar-proto3)), [a recent change](https://github.com/golang/protobuf/commit/da116c3771bf4a398a43f44e069195ef1c9688ef) to `protoc` re-added them. The resulting difference between `go generate` output on my computer vs. that on Wercker had me [briefly confounded](https://github.com/chain/chain/pull/850#issuecomment-291939082).

Whichever version of `protoc` we settle on for CI, let's make sure it's the same one we use for development.

**Comment by boymanjor** [comment]
Fixed by #893
