### ISSUE TITLE
move various wercker scripts into chain/bin

### ISSUE THREAD

**Issue by kr** [chain/chain#891]
Where possible, scripts such as `core-tests` should go in `$CHAIN/bin` so we don't have to rebuild the whole docker image just to edit the wercker logic.

**Comment by boymanjor** [comment]
Wdyt of leaving them in `docker/ci/bin` and adding that directory to the image `PATH`? We could introduce a subdirectory named `install` that could house the scripts we need for the image build. In the Dockerfile we'll only include this new directory. That way we don't pollute $CHAIN/bin with wercker specific scripts. We won't have to rebuild the image unless we update the install scripts.

**Comment by boymanjor** [comment]
Fixed by #893
