### ISSUE TITLE
Reassess timeouts in network protocol & in clients

### ISSUE THREAD

**Issue by jbowens** [chain/chain#900]
**Network protocol consistency**

* RPCs between cored instances propagate timeouts through an HTTP Header: https://github.com/chain/chain/blob/main/core/api.go#L244-L259
* The list-transaction endpoint takes a timeout as a request body parameter:
https://github.com/chain/chain/blob/main/core/api.go#L214

We can deprecate the list-transaction parameter and update existing clients to specify timeouts through the HTTP header.

**Exposing timeouts in SDKs**

Besides the list-transaction endpoint, there's no way to propagate a timeout to cored. At least in the java SDK, we support changing the OkHttp client's read, write & connect timeouts, but these are not propagated to cored.

**Comment by jeffomatic** [comment]
One other issue to roll into this: txfeed long-polling assumes a long client-side timeout setting, but none of the SDKs adjust the client-side timeout for this RPC. Instead, the SDKs assume a generic timeout for all RPCs.

**Comment by tessr** [comment]
Another related issue: We have some fairly arbitrary timeouts sprinkled all over the codebase. 

Examples: 
https://github.com/chain/chain/blob/main/database/raft/raft.go#L393
https://github.com/chain/chain/blob/main/cmd/cored/main.go#L53
https://github.com/chain/chain/blob/main/cmd/cored/main.go#L166
https://github.com/chain/chain/blob/main/core/run.go#L49

There are more, but these are the ones on the top off my head. 

We may want to have a more cohesive timeout strategy. My understanding is that most of these values are either a) copied from some default or b) completely arbitrary, and that the intention here is they're being used as a starting point and we will tweak them moving forward. We may not have the data necessary right now, but there may be more principled ways of approaching this (or tests that can give us useful data), and that's likely worth exploring for 1.3.

**Comment by jbowens** [comment]
> txfeed long-polling assumes a long client-side timeout setting, but none of the SDKs adjust the client-side timeout for this RPC

We might want to keep these timeouts where they're at, but re-issue the request automatically from the SDK if we receive a [CH001](https://github.com/chain/chain/blob/main/core/errors.go#L59) response from the API. For txfeed long-polling, we still need to be able to detect timeouts from network issues relatively quickly. Long timeouts would prevent that.
