### ISSUE TITLE
support versioning for raft

### ISSUE THREAD

**Issue by tessr** [chain/chain#909]
Goal: Protect everything that gets written to disk (namely, the WAL and snapshots) with a version number. 

Current state: Nothing has a version number. This is okay, because the absence of a version number can be interpreted as "version 1."

Moving forward: The cluster will have a "minimum version" which is the earliest version number from each node in the cluster (e.g. if a cluster has one node with version 1 and two with version 2, the minimum version is 1). It is also the minimum version required to join the cluster. Every node in the cluster uses the format from the minimum version, even if that node itself has a newer version. (In the aforementioned cluster, the nodes with version 2 use the format from version 1.)

Whenever a node updates its raft version, it recalculates the cluster's minimum version (which may not change). When the minimum version changes, each node in the cluster then switches over to using the format from the new minimum version. 

We might use the compatibility guidelines from Chain Core to guide what formats are supported by each version. That is, a node with version `n+2` might support formats `n+2` and `n+1` but not `n`. However, the version numbers used for raft do not match Chain Core version numbers, as they are expected to change infrequently.

**Comment by jbowens** [comment]
It seems like there are potentially two things to version: on-disk data and network protocol. Maybe we can get away with maintaining strict backwards compatibility on the protocol and just version on-disk data. On-disk data should/will be the responsibility of the sinkdb package, but net/raft will need to be responsible for the version negotiation.

Currently, the database/sinkdb package is actually insulated from the act of storing data on-disk. Maybe we should start by pushing that into the database/sinkdb package via the State interface.

**Comment by jbowens** [comment]
On a related note, it seems like we need our State interface to implement the etcd/raft.Storage interface too. We currently use the raft.MemoryStorage implementation, but that stores the _entire_ latest snapshot in-memory, which I assume will not be desirable or maybe even feasible. CockroachDB's implementation of the raft.Storage interface might be a useful reference.
