### ISSUE TITLE
Bug: submitting transaction with unbalanced outputs/inputs returns CH000

### ISSUE THREAD

**Issue by jeffomatic** [chain/chain#924]
On recent builds of `main`, submitting a transaction with unbalanced inputs and outputs will yield `CH000` instead of `CH735` (Transaction rejected). For example, the following transaction will fail:

- issue one unit of `gold`
- control 100 units of `gold` in `alice`'s account

This should be considered a userland error rather than a server error.

As a side note, this causes the Node SDK integration tests to fail.

**Comment by bobg** [comment]
We lost the `ErrBadTx` umbrella error that previously was wrapping validation errors (and that is then converted to a `CH735`). Will fix.

**Comment by jeffomatic** [comment]
Thanks @bobg !
