### ISSUE TITLE
Docker: improve the first-run experience

### ISSUE THREAD

**Issue by dominic** [chain/chain#926]
For users getting started with Chain Core, Docker has been a consistently stable option for Windows and Linux users. However, the requirement that users accessing their core through Docker authenticate with a client token adds a great deal of friction to the setup process. We've sought to eliminate this friction on other platforms, and Docker deserves the same quality of experience.

I propose we find a way to remove the client token requirement from Docker. Our image is already named `chaincore/developer`, correctly setting expectations for a developer-friendly experience that isn't readily suitable for production systems.

Some options:

* **Disable client tokens**

    Add a flag `no-auth` (or `development`) that permits all client authorizations.

* **Treat host connections as local**

    Pass the IP of the host system to the Chain Core running inside the Docker container via an environment variable, and treat requests from that IP as if they were localhost as well.

---

In addition, Chain Core's logs, dashboard and API responses should indicate that they are accessing a development service.

**Comment by kr** [comment]
I really like this as long as we can figure out how to do it. We've tossed around the idea of treating host connections as local, but it wasn't obvious how to set that up.

I am not a big fan of `no-auth`, but if @tarcieri says it's cool then okay?

For completeness, here are two more options:

- Do nothing. If we decide this is infeasible or the effort to implement it isn't worth the benefit.
- Delete the docker distribution completely. This isn't the only way in which its UX is poor. So maybe we should discontinue the Chain-Core-on-Docker experiment.

**Comment by tarcieri** [comment]
I would be a fan of enforcing token-based auth at a minimum

**Comment by kr** [comment]
Docker has a "host networking" option that makes the container just use the host's network stack directly. Maybe it would Just Work ™️ if we updated the instructions to include `--network host` on the docker command? (If you attempt to test this, note that it doesn't just work on mac, but docker on mac is weird, so maybe check it out on a linux host.)

**Comment by dominic** [comment]
> it doesn't just work on mac

c'mon docker. But actually that's fine, because the Mac app works great.
